[project]
name = "MyApp"
version = "0.1.0"
source_root = "src"

[project.web]
target = "wasm-html"
source = "src"
main = "src/platforms/web/main.fai"
build_dir = "build/web"

[project.server]
target = "native"
source = "src"
main = "src/platforms/server/main.fai"
build_dir = "build/server"
rpc_server = true

[dependencies]
Forui = "https://github.com/forailang/forui"
HtmlForui = "https://github.com/forailang/html-forui"
Forsqlite = "https://github.com/forailang/forsqlite"

[project.web.dependencies.server.remote.dev]
url = "http://localhost:3040"
